file_format: "2"
id: sp3000_keypad
name: SP3000 Keypad
type: board
url: https://github.com/ceynetics/sp3000-keypad
description: Replacement BLE/USB keyboard for Fuji Frontier SP3000 film scanner
manufacturer: Ceynetics
features:
  - keys
  - encoder
  - underglow
  - battery
outputs:
  - usb
  - ble
